import { chromium } from 'playwright';
const route = process.argv[2] ?? '/new/pokemon/dialga';
const out = process.argv[3] ?? 'shot.png';
const width = Number(process.argv[4] ?? 390);
const dark = process.argv[5] !== 'light';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width, height: 900 }, deviceScaleFactor: 2 });
p.on('pageerror', (e) => console.error('PAGEERROR', e.message));
await p.addInitScript((d) => { try { localStorage.setItem('0', d ? '1' : '0'); } catch { /* */ } }, dark);
await p.goto(`http://localhost:3999/#${route}`, { waitUntil: 'load' });
await p.waitForSelector('.r-hero, .r-loading', { timeout: 15000 }).catch(() => console.error('!! not mounted'));
await p.waitForTimeout(3000);
await p.evaluate(() => document.fonts?.ready).catch(() => {});
await p.screenshot({ path: out, fullPage: true });
await b.close();
console.log('wrote', out);
